package com.example.javadersleri.degiskenler;

public class Odev1 {
    public static void main(String[] args) {
        String ilce = "Merzifon";
        System.out.println("İlçe : " + ilce);
        String kita = "Avustralya";
        System.out.println("Kıta : " + kita);
        String faks = "+90-232-222 8888";
        System.out.println("Faks : " + faks);
        int postaKodu = 05300;
        System.out.println("Posta Kodu : " + postaKodu);
        String instaAdresi = "_serkanavci";
        System.out.println("Instagram Adresi : " + instaAdresi);
        String calistigiBolum = "Bilgi Teknolojileri";
        System.out.println("Çalıştığı Bölüm : " + calistigiBolum);
        int urunMiktari = 250;
        System.out.println("Ürün Miktari : " + urunMiktari);
        String musteriSoyAdi = "Avcı";
        System.out.println("Müşteri Soyadı : " + musteriSoyAdi);
        double odemeMiktari = 49.99;
        System.out.println("Ödeme Miktari : " + odemeMiktari);
        String dogumTarihi = "04.08.2000";
        System.out.println("Doğum Tarihi : " + dogumTarihi);
        double borc = 158.89;
        System.out.println("Borç : " + borc + " TL.");
        String medeniHal = "Bekar";
        System.out.println("Medeni Hal : " + medeniHal);
        String videoYorumu = "Faydalı ve güzel kurgulanmış bir video.";
        System.out.println("Video Yorumu : " + videoYorumu);
        String odemeSaati = "22:45";
        System.out.println("Ödeme Saati : " + odemeSaati);
        double eftMiktari = 89.50;
        System.out.println("Eft Miktarı : " + eftMiktari + " TL.");
        int satilanMiktar = 245;
        System.out.println("Satılan Miktar : " + satilanMiktar);
        String telefonModeli = "Samsung Galaxy A13";
        System.out.println("Telefon Modeli : " + telefonModeli);
        String dergiAdi = "Kunteper";
        System.out.println("Dergi Adı : " + dergiAdi);
        String basimTarihi = "09.12.2022";
        System.out.println("Basım Tarihi : " + basimTarihi);
        double zamMiktari = 99.95;
        System.out.println("Zam Miktarı : " + zamMiktari + " TL.");
        int daireSayisi = 45;
        System.out.println("Daire Sayısı : " + daireSayisi);
        String enlem = "39°57'49.89";
        System.out.println("Enlem : " + enlem);
        String boylam = "32°52'21.67";
        System.out.println("Boylam : " + boylam);
        String yemekAdi = "Tereyağlı lokum";
        System.out.println("Yemek Adı : " + yemekAdi);
        double urunFiyati = 44.99;
        System.out.println("Ürün fiyatı : " + urunFiyati + " TL.");
        String sirket = "Microsoft";
        System.out.println("Şirket Adı : " + sirket);
        String videoAdi = "ASLA SEVMEMEM GEREKEN BİR OYUN: THE DIVISION 2(!)";
        System.out.println("Video Adı : " + videoAdi);
        String muzikSuresi = "3:51";
        System.out.println("Müzik Süresi : " + muzikSuresi + " dakika.");
        double mekanPuani = 4.8;
        System.out.println("Mekan Puanı : " + mekanPuani);
        String dosyaAdi = "Projeler";
        System.out.println("Dosya Adı : " + dosyaAdi);
        String resimFormati = ".jpg";
        System.out.println("Resim Formatı : " + resimFormati);
        String renk = "Bordo";
        System.out.println("Renk : " + renk);
        String renkKodu = "#800000";
        System.out.println("Renk Kodu : " + renkKodu);
        String bilgisayarModeli = "Lenovo Ideapad Gaming 3i";
        System.out.println("Bilgisayar Modeli : " + bilgisayarModeli);
        double ekranBoyutu = 16.1;
        System.out.println("Ekran Boyutu : " + ekranBoyutu + " inch.");
        int kullanimSuresi = 187;
        System.out.println("Kullanım Süresi : " + kullanimSuresi + " dakika.");
        int basinc = 1013;
        System.out.println("Basınç : " + basinc + " milibar");
        String etkinlikGunu = "26.10.2023 Perşembe";
        System.out.println("Etkinlik Günü : " + etkinlikGunu);
        String odemeGunu = "25.10.2023 Çarşamba";
        System.out.println("Ödeme Günü : " + odemeGunu);
        String yolculukCikisTarihi = "30.10.2023";
        System.out.println("Yolculuk Çıkış Tarihi : " + yolculukCikisTarihi);
        String mahalleAdi = "Yeni Mahalle";
        System.out.println("Mahalle Adı : " + mahalleAdi);
        String otobusHatti = "Kızıltepe - Acıbadem - Kadıköy";
        System.out.println("Otobüs Hattı : " + otobusHatti);
        int kullanilanDakika = 45;
        System.out.println("Kullanılan Dakika : " + kullanilanDakika);
        long kargoTakipNo = 1873678991;
        System.out.println("Kargo Takip Numarası : " + kargoTakipNo);
        int kuponSuresi = 24;
        System.out.println("Kupon Süresi : " + kuponSuresi + " saat.");
        String kuponKodu = "ENFES50";
        System.out.println("Kupon Kodu : " + kuponKodu);
        String faturaTarihi = "06.11.2023";
        System.out.println("Fatura Tarihi : " + faturaTarihi);

    }
}
